name: Deploy React (frontend) to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/pages.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: frontend/yarn.lock

      - name: Install deps
        working-directory: frontend
        run: yarn install --frozen-lockfile

      - name: Build
        working-directory: frontend
        # if your package.json's build uses craco, this will just work
        run: yarn build

      - name: Add CNAME for custom domain
        run: echo "aboutme.brainzz.com" > frontend/build/CNAME

      - name: Add SPA fallback (React routing)
        run: cp frontend/build/index.html frontend/build/404.html

      - name: Show build dir
        run: |
          echo "=== SHOW_BUILD_DIR_START ==="
          ls -la frontend/build
          echo "Index exists?"
          if test -f frontend/build/index.html; then
            echo "YES"
          else
            echo "NO"
            exit 1
          fi
          echo "=== SHOW_BUILD_DIR_END ==="

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
